version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: product-sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  api:
    build:
      context: ./src/API
      dockerfile: Dockerfile
    container_name: product-api
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ProductDb;User Id=sa;Password=YourStrong!Passw0rd;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - sqlserver

volumes:
  sql-data:
